<?php
require_once __DIR__ . '/../includes/bootstrap.php';
requireCustomer('login.php');
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$stmt = db()->prepare('SELECT * FROM orders WHERE id = ? AND customer_id = ?');
$stmt->execute([$id, currentCustomer()['id']]);
$order = $stmt->fetch();
if (!$order) { http_response_code(404); exit('Commande introuvable.'); }
$itemsStmt = db()->prepare('SELECT oi.*, p.name FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?'); $itemsStmt->execute([$id]); $items = $itemsStmt->fetchAll();
$steps = ['Commandée', 'Confirmée', 'En préparation', 'Expédiée', 'Livrée'];
$statusIndex = $order['status'] === 'Annulée' ? 0 : (in_array($order['status'], $steps, true) ? array_search($order['status'], $steps) : 1);
$subtotal = 0; foreach ($items as $item) $subtotal += $item['price'] * $item['quantity'];
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Commande #<?= (int)$order['id'] ?> | Woodin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4"><a href="mes-commandes.php">Retour à mes commandes</a><h1 class="mt-3">Commande #<?= (int)$order['id'] ?></h1><p><?= e($order['created_at']) ?> · Statut : <strong><?= e($order['status']) ?></strong></p><div class="row g-2 mb-4"><?php foreach ($steps as $index => $step): ?><div class="col"><div class="card p-2 text-center <?= $index <= $statusIndex ? 'border-success' : '' ?>"><?= $index <= $statusIndex ? 'OK ' : '' ?><?= e($step) ?></div></div><?php endforeach; ?></div><div class="table-responsive"><table class="table bg-white"><thead><tr><th>Produit</th><th>Quantité</th><th>Prix unitaire</th><th>Sous-total</th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><?= e($item['name']) ?></td><td><?= (int)$item['quantity'] ?></td><td><?= number_format($item['price'],0,',',' ') ?> FCFA</td><td><?= number_format($item['price']*$item['quantity'],0,',',' ') ?> FCFA</td></tr><?php endforeach; ?></tbody></table></div><div class="text-end"><p>Sous-total : <?= number_format($subtotal,0,',',' ') ?> FCFA</p><?php if ((float)$order['discount_amount'] > 0): ?><p class="text-success">Réduction : -<?= number_format($order['discount_amount'],0,',',' ') ?> FCFA</p><?php endif; ?><h2>Total payé : <?= number_format($order['total_amount'],0,',',' ') ?> FCFA</h2></div><section class="card p-3 my-3"><h2 class="h5">Informations de livraison</h2><p><?= e($order['customer_name']) ?><br><?= e($order['customer_phone']) ?><br><?= e($customer['city']) ?></p></section><a class="btn btn-warning" href="download-invoice.php?id=<?= (int)$order['id'] ?>" download>Télécharger la facture</a> <a class="btn btn-outline-dark" href="../contact.php">Contacter le service client</a></main></body></html>
