<?php
require_once __DIR__ . '/../includes/bootstrap.php';
requireCustomer('login.php');
$customer = currentCustomer();
$status = isset($_GET['status']) ? $_GET['status'] : '';
$allowed = ['En attente', 'Confirmée', 'Expédiée', 'Livrée', 'Annulée'];
$where = ' WHERE customer_id = ?'; $params = [$customer['id']];
if (in_array($status, $allowed, true)) { $where .= ' AND status = ?'; $params[] = $status; }
$countStmt = db()->prepare('SELECT COUNT(*) FROM orders' . $where); $countStmt->execute($params); $totalPages = max(1, (int)ceil($countStmt->fetchColumn() / 12));
$page = max(1, min($totalPages, (int)(isset($_GET['page']) ? $_GET['page'] : 1))); $params[] = 12; $params[] = ($page - 1) * 12;
$stmt = db()->prepare('SELECT * FROM orders' . $where . ' ORDER BY created_at DESC LIMIT ? OFFSET ?'); foreach ($params as $key => $value) $stmt->bindValue($key + 1, $value, is_int($value) ? PDO::PARAM_INT : PDO::PARAM_STR); $stmt->execute(); $orders = $stmt->fetchAll();
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mes commandes | Woodin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-5"><a href="mon-compte.php">Mon compte</a><h1>Mes commandes</h1><nav class="my-3"><?php foreach (array_merge(['' => 'Toutes'], array_combine($allowed, $allowed)) as $key => $label): ?><a class="btn btn-sm <?= $status === $key ? 'btn-dark' : 'btn-outline-dark' ?>" href="?status=<?= urlencode($key) ?>"><?= e($label) ?></a> <?php endforeach; ?></nav><div class="table-responsive"><table class="table bg-white"><thead><tr><th>Commande</th><th>Date</th><th>Statut</th><th>Montant</th><th>Actions</th></tr></thead><tbody><?php foreach ($orders as $order): ?><tr><td>#<?= (int)$order['id'] ?></td><td><?= e($order['created_at']) ?></td><td><?= e($order['status']) ?></td><td><?= number_format($order['total_amount'],0,',',' ') ?> FCFA</td><td><a href="commande-detail.php?id=<?= (int)$order['id'] ?>">Voir le détail</a> · <a href="../invoices/facture_<?= (int)$order['id'] ?>.pdf" download>Facture PDF</a></td></tr><?php endforeach; ?><?php if (!$orders): ?><tr><td colspan="5">Aucune commande enregistrée.</td></tr><?php endif; ?></tbody></table></div><?php if ($totalPages > 1): ?><p>Page <?= $page ?> / <?= $totalPages ?></p><?php endif; ?></main></body></html>
