<?php
require_once __DIR__ . '/includes/bootstrap.php';
$pageTitle = 'Mon panier | Woodin Cameroun';
$pageDescription = 'Consultez votre panier Woodin et finalisez votre commande.';
$flash = isset($_SESSION['flash']) ? $_SESSION['flash'] : '';
unset($_SESSION['flash']);
$items = cartProducts();
$customer = currentCustomer();
$promoCode = strtoupper(trim(isset($_GET['promo']) ? $_GET['promo'] : ''));
if ($promoCode !== '') {
	$promoStmt = db()->prepare('SELECT id, code FROM discounts WHERE code = ? AND is_active = 1 AND valid_from <= CURDATE() AND valid_until >= CURDATE() AND (usage_limit IS NULL OR usage_count < usage_limit)');
	$promoStmt->execute([$promoCode]);
	$promo = $promoStmt->fetch();
	if ($promo) $_SESSION['applied_discount'] = ['id' => (int)$promo['id'], 'code' => $promo['code']];
}
$checkoutName = $customer ? $customer['full_name'] : '';
$checkoutPhone = $customer ? $customer['phone'] : '';
$checkoutEmail = $customer ? $customer['email'] : '';
include __DIR__ . '/includes/header.php';
?>
<?php if ($customer): ?><script>document.addEventListener('DOMContentLoaded', function () { document.querySelector('[name="customer_name"]').value = <?= json_encode($checkoutName) ?>; document.querySelector('[name="customer_phone"]').value = <?= json_encode($checkoutPhone) ?>; document.querySelector('[name="customer_email"]').value = <?= json_encode($checkoutEmail) ?>; });</script><?php endif; ?>
<?php if ($items): ?><div class="container pt-4"><p>Montant avant réduction : <strong><?= number_format(cartSubtotal(), 0, ',', ' ') ?> FCFA</strong><?php if (cartDiscount() > 0): ?> · Réduction : <strong class="text-success">-<?= number_format(cartDiscount(), 0, ',', ' ') ?> FCFA</strong> · Après réduction : <strong><?= number_format(cartGrandTotal(), 0, ',', ' ') ?> FCFA</strong><?php endif; ?></p></div><?php endif; ?>
<?php if ($items): ?><div class="container pt-4"><form method="post" action="actions/apply_discount.php" class="d-flex gap-2"><input class="form-control" name="code" placeholder="Code promo"><button class="btn btn-dark" type="submit">Appliquer</button></form><?php if (!empty($_SESSION['applied_discount'])): ?><p class="text-success mt-2">Code <?= e($_SESSION['applied_discount']['code']) ?> appliqué.</p><?php endif; ?></div><?php endif; ?>
<?php if (!$customer && $items): ?><div class="container pt-4"><div class="alert alert-info">Déjà client ? <a href="client/login.php">Se connecter</a> · Nouveau client ? <a href="client/register.php">Créer un compte</a> · Vous pouvez aussi continuer en tant qu’invité.</div></div><?php endif; ?>
<main><section class="page-hero"><div class="container"><p class="eyebrow">Votre sélection Woodin</p><h1>Mon panier <em>d'achat</em></h1><div class="breadcrumb"><a href="index.php">Accueil</a><i class="fa-solid fa-chevron-right"></i><span>Panier</span></div></div></section><section class="section section-light cart-page"><div class="container"><?php if ($flash): ?><div class="alert alert-warning"><?= e($flash) ?></div><?php endif; ?><div class="cart-table-wrap"><table class="table cart-table align-middle"><thead><tr><th>Produit</th><th>Prix</th><th>Quantité</th><th>Total</th><th></th></tr></thead><tbody><?php foreach ($items as $item): $quantity = $_SESSION['cart'][$item['id']]; ?><tr><td><strong><?= e($item['name']) ?></strong></td><td><?= number_format($item['price'], 0, ',', ' ') ?> FCFA</td><td><div class="cart-quantity"><form method="post" action="actions/cart.php"><input type="hidden" name="product_id" value="<?= (int)$item['id'] ?>"><input type="hidden" name="action" value="decrease"><button type="submit">-</button></form><span><?= (int)$quantity ?></span><form method="post" action="actions/cart.php"><input type="hidden" name="product_id" value="<?= (int)$item['id'] ?>"><input type="hidden" name="action" value="increase"><button type="submit">+</button></form></div></td><td><strong><?= number_format($item['price'] * $quantity, 0, ',', ' ') ?> FCFA</strong></td><td><form method="post" action="actions/cart.php"><input type="hidden" name="product_id" value="<?= (int)$item['id'] ?>"><input type="hidden" name="action" value="remove"><button class="cart-remove" type="submit" aria-label="Supprimer"><i class="fa-solid fa-trash"></i></button></form></td></tr><?php endforeach; ?></tbody></table><?php if (!$items): ?><p class="empty-state">Votre panier est encore vide. <a href="catalogue.php">Découvrir le catalogue</a></p><?php endif; ?></div><div class="cart-summary"><span>TOTAL GÉNÉRAL</span><strong><?= number_format(cartTotal(), 0, ',', ' ') ?> FCFA</strong></div><div class="cart-actions"><form method="post" action="actions/clear_cart.php"><button class="btn btn-danger" type="submit"><i class="fa-solid fa-trash"></i> Vider le panier</button></form></div><?php if ($items): ?><form class="checkout-form" method="post" action="actions/place_order.php"><h2>Finaliser la commande</h2><div class="row g-3"><div class="col-md-4"><input class="form-control" name="customer_name" required placeholder="Nom complet"></div><div class="col-md-4"><input class="form-control" name="customer_phone" required placeholder="Téléphone"></div><div class="col-md-4"><input class="form-control" name="customer_email" type="email" required placeholder="Email de confirmation"></div></div><button class="btn btn-gold mt-3" type="submit"><i class="fa-solid fa-lock"></i> Procéder au paiement</button></form><?php endif; ?></div></section></main><?php include __DIR__ . '/includes/footer.php'; ?>
