CREATE DATABASE IF NOT EXISTS `woodin_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `woodin_db`;

CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `image_url` varchar(255) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `stock` (`stock`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `products_category_fk` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `admins` (`id` int(11) NOT NULL AUTO_INCREMENT,`username` varchar(50) NOT NULL,`password` varchar(255) NOT NULL,`role` enum('super_admin','gestionnaire') NOT NULL DEFAULT 'gestionnaire',`is_active` tinyint(1) NOT NULL DEFAULT 1,`last_login` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `username` (`username`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `login_attempts` (`id` int(11) NOT NULL AUTO_INCREMENT,`username` varchar(50) NOT NULL,`ip_address` varchar(45) NOT NULL,`attempted_at` timestamp NOT NULL DEFAULT current_timestamp(),`locked_until` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `login_attempt_lookup` (`username`,`ip_address`,`attempted_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `customers` (`id` int(11) NOT NULL AUTO_INCREMENT,`full_name` varchar(255) NOT NULL,`email` varchar(191) NOT NULL,`phone` varchar(30) DEFAULT NULL,`password` varchar(255) DEFAULT NULL,`city` varchar(100) NOT NULL DEFAULT '',`google_id` varchar(191) DEFAULT NULL,`apple_id` varchar(191) DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),UNIQUE KEY `customer_email` (`email`),UNIQUE KEY `customer_phone` (`phone`),UNIQUE KEY `customer_google_id` (`google_id`),UNIQUE KEY `customer_apple_id` (`apple_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `customer_login_attempts` (`id` int(11) NOT NULL AUTO_INCREMENT,`identifier` varchar(255) NOT NULL,`ip_address` varchar(45) NOT NULL,`attempted_at` timestamp NOT NULL DEFAULT current_timestamp(),`locked_until` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `customer_login_lookup` (`identifier`,`ip_address`,`attempted_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `password_resets` (`id` int(11) NOT NULL AUTO_INCREMENT,`customer_id` int(11) NOT NULL,`token_hash` char(64) NOT NULL,`expires_at` datetime NOT NULL,`used_at` datetime NULL DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),UNIQUE KEY `password_reset_token` (`token_hash`),KEY `password_reset_customer` (`customer_id`),CONSTRAINT `password_reset_customer_fk` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `orders` (`id` int(11) NOT NULL AUTO_INCREMENT,`customer_id` int(11) DEFAULT NULL,`customer_name` varchar(255) NOT NULL,`customer_phone` varchar(255) NOT NULL,`customer_email` varchar(255) NOT NULL DEFAULT '',`total_amount` decimal(10,2) NOT NULL,`discount_amount` decimal(10,2) NOT NULL DEFAULT 0,`status` varchar(50) NOT NULL DEFAULT 'En attente',`invoice_token` varchar(32) DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),UNIQUE KEY `invoice_token` (`invoice_token`),KEY `status` (`status`),KEY `order_customer` (`customer_id`),CONSTRAINT `orders_customer_fk` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `order_items` (`id` int(11) NOT NULL AUTO_INCREMENT,`order_id` int(11) NOT NULL,`product_id` int(11) NOT NULL,`quantity` int(11) NOT NULL,`price` decimal(10,2) NOT NULL,PRIMARY KEY (`id`),KEY `order_id` (`order_id`),KEY `product_id` (`product_id`),CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `messages` (`id` int(11) NOT NULL AUTO_INCREMENT,`nom` varchar(255) NOT NULL,`email` varchar(255) NOT NULL,`telephone` varchar(50) NOT NULL DEFAULT '',`message` text NOT NULL,`created_at` timestamp NOT NULL DEFAULT current_timestamp(),`lu` tinyint(1) NOT NULL DEFAULT 0,`is_read` tinyint(1) NOT NULL DEFAULT 0,PRIMARY KEY (`id`),KEY `message_read_status` (`is_read`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `product_images` (`id` int(11) NOT NULL AUTO_INCREMENT,`product_id` int(11) NOT NULL,`image_url` varchar(255) NOT NULL,`is_main` tinyint(1) NOT NULL DEFAULT 0,PRIMARY KEY (`id`),KEY `product_images_product` (`product_id`),CONSTRAINT `product_images_product_fk` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `stock_movements` (`id` int(11) NOT NULL AUTO_INCREMENT,`product_id` int(11) NOT NULL,`quantity_change` int(11) NOT NULL,`reason` enum('vente','réapprovisionnement','correction','annulation_commande') NOT NULL,`created_at` timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),KEY `stock_movements_product` (`product_id`),CONSTRAINT `stock_movements_product_fk` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `discounts` (`id` int(11) NOT NULL AUTO_INCREMENT,`code` varchar(50) NOT NULL,`type` enum('percentage','fixed') NOT NULL,`value` decimal(10,2) NOT NULL,`min_purchase_amount` decimal(10,2) DEFAULT NULL,`usage_limit` int(11) DEFAULT NULL,`usage_count` int(11) NOT NULL DEFAULT 0,`valid_from` date NOT NULL,`valid_until` date NOT NULL,`is_active` tinyint(1) NOT NULL DEFAULT 1,PRIMARY KEY (`id`),UNIQUE KEY discount_code (`code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `product_promotions` (`id` int(11) NOT NULL AUTO_INCREMENT,`product_id` int(11) NOT NULL,`discount_percentage` decimal(5,2) NOT NULL,`starts_at` date NOT NULL,`ends_at` date NOT NULL,PRIMARY KEY (`id`),KEY promotion_product (`product_id`),CONSTRAINT promotion_product_fk FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `discount_usage` (`id` int(11) NOT NULL AUTO_INCREMENT,`customer_id` int(11) NOT NULL,`discount_id` int(11) NOT NULL,`order_id` int(11) NOT NULL,`used_at` timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),KEY discount_usage_customer (`customer_id`),KEY discount_usage_discount (`discount_id`),UNIQUE KEY discount_usage_order (`order_id`),CONSTRAINT discount_usage_customer_fk FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,CONSTRAINT discount_usage_discount_fk FOREIGN KEY (`discount_id`) REFERENCES `discounts` (`id`) ON DELETE RESTRICT,CONSTRAINT discount_usage_order_fk FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `order_status_history` (`id` int AUTO_INCREMENT PRIMARY KEY,`order_id` int NOT NULL,`old_status` varchar(50) NULL,`new_status` varchar(50) NOT NULL,`changed_by` int NOT NULL COMMENT 'admin_id',`changed_at` timestamp DEFAULT CURRENT_TIMESTAMP,`note` text NULL,FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,FOREIGN KEY (`changed_by`) REFERENCES `admins` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `categories` (`name`, `slug`) VALUES ('4 yards', '4-yards'), ('6 yards', '6-yards'), ('Prêt-à-porter', 'pret-a-porter') ON DUPLICATE KEY UPDATE name=VALUES(name);

INSERT INTO `products` (`name`,`description`,`price`,`stock`,`image_url`) SELECT * FROM (SELECT 'Pagne Collection Succès 6 yards','Tissu wax 100% coton, motif exclusif Woodin.',39000.00,20,'assets/images/pagne_succes.jpg' UNION ALL SELECT 'Pagne Collection MaxiOr 6 yards','Collection vibrante et moderne, idéale pour toutes occasions.',29000.00,15,'assets/images/pagne_maxior.jpg' UNION ALL SELECT 'Pagne Collection Royal 6 yards','Élégance et prestige avec des motifs royaux.',29000.00,10,'assets/images/pagne_royal.jpg' UNION ALL SELECT 'Pagne du Ghana 4 yards','Motifs traditionnels du Ghana, parfait pour des tenues légères.',15000.00,30,'assets/images/pagne_ghana.jpg' UNION ALL SELECT 'Haut croisé en pagne','Prêt-à-porter chic et moderne, confectionné avec nos meilleurs tissus.',28000.00,25,'assets/images/haut_croise.jpg') AS seed WHERE NOT EXISTS (SELECT 1 FROM products LIMIT 1);
UPDATE `products` SET `category_id` = (SELECT `id` FROM `categories` WHERE `slug` = CASE WHEN `name` LIKE '%4 yards%' THEN '4-yards' WHEN `name` LIKE '%6 yards%' THEN '6-yards' ELSE 'pret-a-porter' END LIMIT 1) WHERE `category_id` IS NULL;
INSERT INTO `admins` (`username`,`password`,`role`) VALUES ('admin','$2y$10$EwTsA5aU0eSk.3xbQ3pSw.MyXs/3Z3xRNdafKEVhKpC.QGirhiEDa','super_admin') ON DUPLICATE KEY UPDATE password=VALUES(password), role='super_admin';
