<?php
require_once __DIR__ . '/auth.php';
$flash = isset($_SESSION['admin_flash']) ? $_SESSION['admin_flash'] : '';
unset($_SESSION['admin_flash']);
$filter = isset($_GET['filter']) ? $_GET['filter'] : '';
$orderWhere = $filter === 'en_attente' ? " WHERE status = 'En attente'" : ($filter === 'en_attente_48h' ? " WHERE status = 'En attente' AND created_at < DATE_SUB(NOW(), INTERVAL 48 HOUR)" : '');
$stmt = $pdo->prepare('SELECT * FROM orders' . $orderWhere . ' ORDER BY created_at DESC');
$stmt->execute();
$orders = $stmt->fetchAll();
$statuses = ['En attente', 'Confirmée', 'Expédiée', 'Annulée'];
?>
<script>document.addEventListener('DOMContentLoaded', function () { document.querySelectorAll('table tbody tr').forEach(function (row) { var id = row.querySelector('td'); var target = row.lastElementChild; if (id && target) { var link = document.createElement('a'); link.className = 'btn btn-sm btn-outline-dark ms-2'; link.href = 'invoice.php?id=' + encodeURIComponent(id.textContent.trim()); link.textContent = 'Voir/Télécharger la facture PDF'; target.appendChild(link); } }); });</script>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Commandes | Woodin Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand text-warning" href="index.php">WOODIN ADMIN</a><a class="btn btn-warning btn-sm" href="logout.php">Déconnexion</a></div></nav><main class="container py-4"><h1>Commandes</h1><?php if ($flash): ?><div class="alert alert-info"><?= e($flash) ?></div><?php endif; ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>Client</th><th>Téléphone</th><th>Total</th><th>Statut</th><th>Date</th></tr></thead><tbody><?php foreach ($orders as $order): ?><tr><td><?= (int)$order['id'] ?></td><td><?= e($order['customer_name']) ?></td><td><?= e($order['customer_phone']) ?></td><td><?= number_format($order['total_amount'], 0, ',', ' ') ?> FCFA</td><td><form method="post" action="update_order_status.php" class="d-flex gap-2"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><select name="status" class="form-select form-select-sm"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= $status === $order['status'] ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-warning" type="submit">Mettre à jour</button></form></td><td><?= e($order['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></main></body></html>
